# pyproject.toml

[tool.ruff]
# Linter + formateo (Ruff también puede formatear)
line-length = 100
target-version = "py311"            
extend-exclude = [".venv"]

[tool.ruff.lint]
# Reglas por defecto; puedes ampliar con select si lo deseas
select = ["E", "F", "I"]            # E,F (pycodestyle/pyflakes), I (import order)

[tool.ruff.format]
# Activar formateo de Ruff
quote-style = "double"

[tool.mypy]
python_version = "3.11"
strict = true
warn_return_any = true
warn_unused_ignores = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
no_implicit_optional = true
check_untyped_defs = true

# rutas/fuentes a analizar:
files = ["src"]

# ignore_missing_imports = true
