name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  lint-type-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ruff
        run: |
          ruff check .
          ruff format --check .
      - name: Mypy
        run: mypy .
      - name: Pytest
        run: pytest -q
